id: NiryoNed
action_type: task
task: Faro
speed: 2
movement_type: default
home_pose:
  x: 0.0
  y: 0
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 0.00
place_pose:
  x: 0.224
  y: -0.015
  z: 0.203
  roll: -1.721
  pitch: 1.508
  yaw: -1.712
pick_list:
  pick1:
    x: -0.120
    y: 0.336
    z: 0.074
    roll: -2.068
    pitch: 1.531
    yaw: -0.416
  pick2:
    x: -0.117
    y: 0.434
    z: 0.071
    roll: -2.128
    pitch: 1.509
    yaw: -0.495
  pick3:
    x: -0.048
    y: 0.434
    z: 0.075
    roll: -1.959
    pitch: 1.520
    yaw: -0.323
  pick4:
    x: 0.021
    y: 0.436
    z: 0.078
    roll: -2.959
    pitch: 1.538
    yaw: -1.336
  pick5:
    x: 0.012
    y: 0.213
    z: 0.082
    roll: -3.043
    pitch: 1.525
    yaw: -1.385
  pick6:
    x: -0.048
    y: 0.328
    z: 0.075
    roll: -2.954
    pitch: 1.509
    yaw: -1.330
  pick7:
    x: -0.188
    y: 0.331
    z: 0.073
    roll: -0.996
    pitch: 1.524
    yaw: 0.639
  pick8:
    x: -0.126
    y: 0.216
    z: 0.083
    roll: -2.463
    pitch: 1.545
    yaw: -0.807
  pick9:
    x: -0.062
    y: 0.216
    z: 0.083
    roll: -2.359
    pitch: 1.501
    yaw: -0.708
  pick10:
    x: 0.015
    y: 0.327
    z: 0.084
    roll: -2.370
    pitch: 1.516
    yaw: -0.728